### ISSUE TITLE
Create a Github Action for pip-rating

### ISSUE THREAD

**Issue by cygnusv** [Nekmo/pip-rating#37]
### Describe your suggested feature

So instead of using pip-rating as a standalone CLI tool, other projects can run it as part of their CI workflow.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Nekmo** [comment]
The suggestion has been scheduled for version 0.2.0. Thanks!

**Comment by Nekmo** [comment]
Github actions is now available and documented: https://docs.nekmo.org/pip-rating/github_action.html

I hope you can enjoy it.

**Comment by Nekmo** [comment]
This is now available in the marketplace:
https://github.com/marketplace/actions/pip-rating
